:page-title: Convert Number Argument to Byte Array
:page-description: The JUnit 5 (Jupiter) extension `@NumberToByteArrayConversion` convert the number value of an argument to its byte array representation
:xp-demo-dir: ../src/demo/java
:demo: {xp-demo-dir}/org/junitpioneer/jupiter/converter/ByteArrayConverterDemo.java

In some use-cases (e.g.: bitwise operations) you might want to work with numbers in a byte array form.
The conversion from number to byte array in this case would ideally not be part of your test.
By applying `@NumberToByteArrayConversion` on the parameter you want to convert, you can immediately start working with a `byte[]` in your test.

== `@NumberToByteArrayConversion`

When applied to a parameter supplied with a number by `@ValueSource`, `@NumberToByteArrayConversion` converts the number to its `byte[]` representation.
To showcase with some examples:
[source,java,indent=0]
----
include::{demo}[tag=int_example]

include::{demo}[tag=long_example]
----

By default, the extension uses big endian order.
This can be configured in the annotation using `order`.

[source,java,indent=0]
----
include::{demo}[tag=little_endian_order]
----

The extension will support `byte`, `short`, `int`, `long`, `double` and `float`.
It does not support `String`.

== Thread-Safety

This extension is safe to use during https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution[parallel test execution].
