:page-title: Default Locale and TimeZone
:page-description: Extends JUnit Jupiter with `@DefaultLocale`, `@DefaultTimeZone`, which change the values returned from Locale.getDefault() and TimeZone.getDefault()

The `@DefaultLocale` and `@DefaultTimeZone` annotations can be used to change the values returned from `Locale.getDefault()` and `TimeZone.getDefault()`.
Both annotations work on the test class level and on the test method level.
After the annotated element has been executed the initial default value is restored.

== `@DefaultLocale`

The default `Locale` can be specified using an https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#forLanguageTag-java.lang.String-[IETF BCP 47 language tag string]

[source,java]
----
@Test
@DefaultLocale("zh-Hant-TW")
void test_with_lanuage() {
	assertThat(Locale.getDefault())
		.isEqualTo(Locale.forLanguageTag("zh-Hant-TW"));
}
----

Alternatively the default `Locale` can be specified according to https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#constructor.summary[its constructors] - it needs either:

* `language` or
* `language` and `country` or
* `language`, `country`, and `variant`

[source,java]
----
@Test
@DefaultLocale(language = "en")
void test_with_lanuage() {
	assertThat(Locale.getDefault())
		.isEqualTo(new Locale("en"));
}

@Test
@DefaultLocale(language = "en", country = "EN")
void test_with_lanuage_and_country() {
	assertThat(Locale.getDefault())
		.isEqualTo(new Locale("en", "EN"));
}

@Test
@DefaultLocale(
	language = "en",
	country = "EN",
	variant = "gb")
void test_with_lanuage_and_country_and_vairant() {
	assertThat(Locale.getDefault())
		.isEqualTo(new Locale("en", "EN", "gb"));
}
----

Note that mixing language tag configuration and constructor based configuration will cause an `ExtensionConfigurationException` to be thrown.
Furthermore a `variant` can only be specified if `country` is also specified.
If `variant` is specified without `country`, an `ExtensionConfigurationException` will be thrown.

Any method level `@DefaultLocale` configurations will override class level configurations.

[source,java]
----
@DefaultLocale(language = "fr")
class MyLocaleTests {

	@Test
	void test_with_class_level_configuration() {
		assertThat(Locale.getDefault())
			.isEqualTo(new Locale("fr"));
	}

	@Test
	@DefaultLocale(language = "en")
	void test_with_method_level_configuration() {
		assertThat(Locale.getDefault())
			.isEqualTo(new Locale("en"));
	}
}
----

NOTE: A class-level configuration means that the specified locale is set before and reset after each individual test in the annotated class.

== `@DefaultTimeZone`

The default `TimeZone` is specified according to the https://docs.oracle.com/javase/8/docs/api/java/util/TimeZone.html#getTimeZone(java.lang.String)[TimeZone.getTimeZone(String)] method.

[source,java]
----
@Test
@DefaulTimeZone("CET")
void test_with_short_zone_id() {
	assertThat(TimeZone.getDefault()).
		isEqualTo(TimeZone.getTimeZone("CET"));
}

@Test
@DefaultTimeZone("Africa/Juba")
void test_with_long_zone_id() {
	assertThat(TimeZone.getDefault()).
		isEqualTo(TimeZone.getTimeZone("Africa/Juba"));
}
----

Any method level `@DefaultTimeZone` configurations will override class level configurations:

[source,java]
----
@DefaultTimeZone("CET")
class MyTimeZoneTests {

	@Test
	void test_with_class_level_configuration() {
		assertThat(TimeZone.getDefault()).
			isEqualTo(TimeZone.getTimeZone("CET"));
	}

	@Test
	@DefaultTimeZone("Africa/Juba")
	void test_with_method_level_configuration() {
		assertThat(TimeZone.getDefault()).
			isEqualTo(TimeZone.getTimeZone("Africa/Juba"));
	}
}
----

NOTE: A class-level configuration means that the specified time zone is set before and reset after each individual test in the annotated class.

== Thread-Safety

Since default locale and time zone are global state, reading and writing them during https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution[parallel test execution] can lead to unpredictable results and flaky tests.
The `@DefaultLocale` and `@DefaultTimeZone` extensions are prepared for that and tests annotated with them will never execute in parallel (thanks to https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/parallel/ResourceLock.html[resource locks]) to guarantee correct test results.

However, this does not cover all possible cases.
Tested code that reads or writes default locale and time zone _independently_ of the extensions can still run in parallel to them and may thus behave erratically when, for example, it unexpectedly reads a locale set by the extension in another thread.
Tests that cover code that reads or writes the default locale or time zone need to be annotated with the respective annotation:

* `@ReadsDefaultLocale`
* `@ReadsDefaultTimeZone`
* `@WritesDefaultLocale`
* `@WritesDefaultTimeZone`

Tests annotated in this way will never execute in parallel with tests annotated with `@DefaultLocale` or `@DefaultTimeZone`.
