:page-title: Default Locale and TimeZone
:page-description: Extends JUnit Jupiter with `@DefaultLocale`, `@DefaultTimeZone`, which change the values returned from Locale.getDefault() and TimeZone.getDefault()
:xp-demo-dir: ../src/demo/java
:demo: {xp-demo-dir}/org/junitpioneer/jupiter/DefaultLocaleTimezoneExtensionDemo.java

The `@DefaultLocale` and `@DefaultTimeZone` annotations can be used to change the values returned from `Locale.getDefault()` and `TimeZone.getDefault()`.
Both annotations work on the test class level and on the test method level, and are inherited from higher-level containers.
After the annotated element has been executed the initial default value is restored.

== `@DefaultLocale`

The default `Locale` can be specified using an https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#forLanguageTag-java.lang.String-[IETF BCP 47 language tag string]

[source,java,indent=0]
----
include::{demo}[tag=default_locale_language]
----

Alternatively the default `Locale` can be specified according to https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#constructor.summary[its constructors] - it needs either:

* `language` or
* `language` and `country` or
* `language`, `country`, and `variant`

[source,java,indent=0]
----
include::{demo}[tag=default_locale_language_alternatives]
----

Note that mixing language tag configuration and constructor based configuration will cause an `ExtensionConfigurationException` to be thrown.
Furthermore a `variant` can only be specified if `country` is also specified.
If `variant` is specified without `country`, an `ExtensionConfigurationException` will be thrown.

Any method level `@DefaultLocale` configurations will override class level configurations.

[source,java,indent=0]
----
include::{demo}[tag=default_locale_class_level]
----

NOTE: A class-level configuration means that the specified locale is set before and reset after each individual test in the annotated class.

== `@DefaultTimeZone`

The default `TimeZone` is specified according to the https://docs.oracle.com/javase/8/docs/api/java/util/TimeZone.html#getTimeZone-java.lang.String-[TimeZone.getTimeZone(String)] method.

[source,java,indent=0]
----
include::{demo}[tag=default_timezone_zone]
----

Any method level `@DefaultTimeZone` configurations will override class level configurations:

[source,java,indent=0]
----
include::{demo}[tag=default_timezone_class_level]
----

NOTE: A class-level configuration means that the specified time zone is set before and reset after each individual test in the annotated class.

== Thread-Safety

Since default locale and time zone are global state, reading and writing them during https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution[parallel test execution] can lead to unpredictable results and flaky tests.
The `@DefaultLocale` and `@DefaultTimeZone` extensions are prepared for that and tests annotated with them will never execute in parallel (thanks to https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/parallel/ResourceLock.html[resource locks]) to guarantee correct test results.

However, this does not cover all possible cases.
Tested code that reads or writes default locale and time zone _independently_ of the extensions can still run in parallel to them and may thus behave erratically when, for example, it unexpectedly reads a locale set by the extension in another thread.
Tests that cover code that reads or writes the default locale or time zone need to be annotated with the respective annotation:

* `@ReadsDefaultLocale`
* `@ReadsDefaultTimeZone`
* `@WritesDefaultLocale`
* `@WritesDefaultTimeZone`

Tests annotated in this way will never execute in parallel with tests annotated with `@DefaultLocale` or `@DefaultTimeZone`.
