:page-title: @DefaultLocale and @DefaultTimeZone
:page-description: JUnit Jupiter extensions to change the values returned from Locale.getDefault() and TimeZone.getDefault()

The `@DefaultLocale` and `@DefaultTimeZone` annotations can be used to change the values returned from `Locale.getDefault()` and `TimeZone.getDefault()`.
Both annotations work on the test class level and on the test method level.
After the annotated element has been executed the initial default value is restored.

== `@DefaultLocale`

The default `Locale` can be specified using an https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#forLanguageTag-java.lang.String-[IETF BCP 47 language tag string]

[source,java]
----
@Test
@DefaultLocale("zh-Hant-TW")
void test_with_lanuage() {
	assertThat(Locale.getDefault()).isEqualTo(Locale.forLanguageTag("zh-Hant-TW"));
}
----

Alternatively the default `Locale` can be specified according to https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#constructor.summary[its constructors] - it needs either:

* `language` or
* `language` and `country` or
* `language`, `country`, and `variant`

[source,java]
----
@Test
@DefaultLocale(language = "en")
void test_with_lanuage() {
	assertThat(Locale.getDefault()).isEqualTo(new Locale("en"));
}

@Test
@DefaultLocale(language = "en", country = "EN")
void test_with_lanuage_and_country() {
	assertThat(Locale.getDefault()).isEqualTo(new Locale("en", "EN"));
}

@Test
@DefaultLocale(language = "en", country = "EN", variant = "gb")
void test_with_lanuage_and_country_and_vairant() {
	assertThat(Locale.getDefault()).isEqualTo(new Locale("en", "EN", "gb"));
}
----

Note that mixing language tag configuration and constructor based configuration will cause an `ExtensionConfigurationException` to be thrown.
Furthermore a `variant` can only be specified if `country` is also specified.
If `variant` is specified without `country`, an `ExtensionConfigurationException` will be thrown.

Any method level `@DefaultLocale` configurations will override class level configurations.

[source,java]
----
@DefaultLocale(language = "fr")
class MyLocaleTests {

	@Test
	void test_with_class_level_configuration() {
		assertThat(Locale.getDefault()).isEqualTo(new Locale("fr"));
	}

	@Test
	@DefaultLocale(language = "en")
	void test_with_method_level_configuration() {
		assertThat(Locale.getDefault()).isEqualTo(new Locale("en"));
	}
}
----

== `@DefaultTimeZone`

The default `TimeZone` is specified according to the https://docs.oracle.com/javase/8/docs/api/java/util/TimeZone.html#getTimeZone(java.lang.String)[TimeZone.getTimeZone(String)] method.

[source,java]
----
@Test
@DefaulTimeZone("CET")
void test_with_short_zone_id() {
	assertThat(TimeZone.getDefault()).isEqualTo(TimeZone.getTimeZone("CET"));
}

@Test
@DefaultTimeZone("America/Los_Angeles")
void test_with_long_zone_id() {
	assertThat(TimeZone.getDefault()).isEqualTo(TimeZone.getTimeZone("America/Los_Angeles"));
}
----

Any method level `@DefaultTimeZone` configurations will override class level configurations:

[source,java]
----
@DefaultTimeZone("CET")
class MyTimeZoneTests {

	@Test
	void test_with_class_level_configuration() {
		assertThat(TimeZone.getDefault()).isEqualTo(TimeZone.getTimeZone("CET"));
	}

	@Test
	@DefaultTimeZone("America/Los_Angeles")
	void test_with_method_level_configuration() {
        assertThat(TimeZone.getDefault()).isEqualTo(TimeZone.getTimeZone("America/Los_Angeles"));
	}
}
----
