:page-title: Free Port
:page-description: Extends JUnit Jupiter with `@FreePort` to get a free port.
:xp-demo-dir: ../src/demo/java
:demo: {xp-demo-dir}/org/junitpioneer/jupiter/resource/FreePortDemo.java

== Introduction

Sometimes we want a free socket in our tests so that we can either start a server on it or to test a failure scenario when there is no service at the given port.

FreePort is an implementation of link:/docs/resources.adoc[`ResourceFactory`] that opens a `java.net.ServerSocket`.
You can use this simple utility in one of two ways.

 1. Create a new socket for your test with `@New`.
 2. Create a socket that's shared between tests with `@Shared`.

You can read more about how these annotations work in the link:/docs/resources.adoc[Resource Extension documentation].

You don't have to worry about closing the socket.
This is done automatically at the end of their respective scope (e.g.: the test, in case of `@New`).

== Usage

If you just need any random port open for a single test, you can do:

[source,java,indent=0]
----
include::{demo}[tag=basic_free_port_example]
----

If you need a specific port open, you can supply your arguments in the annotation:

[source,java,indent=0]
----
include::{demo}[tag=specific_port_example]
----