:page-title: Issue Information
:page-description: Extends JUnit Jupiter with `@Issue` to publish issue information.


== Introduction

The main reason developer write tests is to ensure the functionality of a requirement or to avoid technical problems.
The `@Issue` annotation allows marking tests with a String, referencing a related issue (like a requirement or a bugfix) of an issue-tracker (like JIRA or Redmine).

It's a JUnit Jupiter extension for showing that tests exist to cover an specific issue.
The annotated issue will be enlisted in the test results, so that it's easy so see if all tests of an issue are completed successfully.

== Usage

To show that a test related to an issue just add the annotation and provide a value, e.g. a JIRA issue, like in the following example:

[source,java]
----
@Issue("REQ-123")
@Test
void test() {
	// One of the tests for the issue with the id "REQ-123"
}
----

The `@Issue` annotation can be used on the method level only.
This is done on purpose, so that the test class can contain tests which cover the professional requirements but also tests which only exist to ensure technical functionality / implementation details.

The `@Issue` annotation can only be used once per method.
This is done on purpose too, because a test case should only cover exactly one aspect of a method.


