:page-title: JSON
:page-description: Extends JUnit Jupiter with `@JsonFileSource`, a parametrized test that creates test based on a JSON Source

The `@JsonFileSource` annotation lets you use JSON files from the classpath or local file system to create parametrized tests.
The `@JsonSource` annotation lets you use lenient JSON values to create parametrized tests.

There are various ways how the method arguments for a single parametrized test are provided.
By default the root of the source will be treated as candidate for the test arguments.
If the root is an object then the entire object will be one argument, if the root is an array then every element of the array will be one argument.

It is also possible to use a nested array from the provided JSON to access the source for the test arguments.
The `JsonFileSource#data` can be used to tell the extraction mechanism to use the element with that name to look for the source of the data.

Depending on the test method parameters, the extraction of the values might differ.

== Method Arguments

=== Single Argument Methods

If the method has a single argument, the json object argument will be converted to that type.

.Argument type
[source,java]
----
public class Jedi {
	public String name;
	public String height;

	@Override
    public String toString() {
        return "Jedi {" + "name='" + name + '\'' + ", height=" + height + '}';
    }
}
----

.JSON Source
[source,json]
----
[
  {
    "name": "Luke",
    "height": 172
  },
  {
    "name": "Yoda",
    "height": 66
  }
]
----

[source,java]
----
@ParametrizedTest
@JsonFileSource(resources = "/jedis.json")
void singleJedi(Jedi jedi) {
    // Assertions
}
----

[source,java]
----
@ParametrizedTest
@JsonSource("["
        + "  { name: 'Luke', height: 172  },"
        + "  { name: 'Yoda', height: 66 }"
        + "]")
void singleJedi(Jedi jedi) {
    // Assertions
}
----

This parametrized test will generate the following test executions:

* [1] Jedi {name='Luke', height=172}
* [2] Jedi {name='Yoda', height=66}

It is also possible to extract only a single element from each argument object by using the `@Property` annotation.

[source,java]
----
@ParametrizedTest
@JsonFileSource(resources = "/jedis.json")
void singleJedi(@Property("name") String jediName) {
    // Assertions
}
----

[source,java]
----
@ParametrizedTest
@JsonSource({
            "{ name: 'Luke', height: 172  }",
            "{ name: 'Yoda', height: 66 }"
        })
void singleJedi(@Property("name") String jediName) {
    // Assertions
}
----

This parametrized test will generate the following tests:

* [1] Luke
* [2] Yoda

=== Multiple Argument Methods

If the method has multiple arguments, each json object argument will be deconstructed to each of the method arguments.
By default, the method argument name will be used for locating the element that needs to be taken from the json object.
You can also use `@Property` to give the name of the element that needs to be extracted.

[IMPORTANT]
====
If your test sources are not compiled using the `--parameters` flag then the names of the arguments will not be like they are written in the source code.
In that the situation you need to use `@Property` instead.
====

Using the same `jedis.json` and the following test

[source,java]
----
@ParametrizedTest
@JsonFileSource(resources = "/jedis.json")
void deconstructFromArray(@Property("name") String name, @Property("height") int height) {
    // Assertions
}
----

[source,java]
----
@ParametrizedTest
@JsonSource({
            "{ name: 'Yoda', height: 66 }",
            "{ name: 'Luke', height: 172 }",
        })
void deconstructFromArray(@Property("name") String name, @Property("height") int height) {
    // Assertions
}
----

This parametrized test will generate the following tests:

* [1] Luke, 172
* [2] Yoda, 66

== Extracting nested array

Sometimes we want to extract a nested array instead of the root element.
For this purpose `JsonFileSource#data` can be used.

.Jedi with nested array
[source,json]
----
{
  "name": "Luke",
  "height": 172,
  "vehicles": [
    {
      "name": "Snowspeeder",
      "length": 4.5
    },
    {
      "name": "Imperial Speeder Bike",
      "length": 3
    }
  ]
}
----

Here we want to test the vehicles.
The test for this will look like:

[source,java]
----
@ParameterizedTest
@JsonFileSource(resources = "luke.json", data = "vehicles")
void lukeVehicles(@Property("name") String name, @Property("length") double length) {
    // Assertions
}
----

This parametrized test will generate the following tests:

* [1] Snowspeeder, 4.5
* [2] Imperial Speeder Bike, 3

== Thread-Safety

This extension is safe to use during https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution[parallel test execution].
