:page-title: Range Sources
:page-description: The JUnit 5 (Jupiter) extensions `@IntRangeSource`, `@FloatRangeSource`, etc. provide series of numbers as argument sources for parameterized tests
:xp-demo-dir: ../src/demo/java
:demo: {xp-demo-dir}/org/junitpioneer/jupiter/params/RangeSourcesDemo.java

The various range sources can be used to provide a series of numeric arguments with fixed differences between them (i.e., https://en.wikipedia.org/wiki/Arithmetic_progression[arithmetic progressions]) to a `@ParameterizedTest`.
There is a range source for every corresponding numeric primitive type: `ByteRangeSource`, `ShortRangeSource`, `IntRangeSource`, `LongRangeSource`, `FloatRangeSource`, and `DoubleRangeSource`.

== Basic Use

In the basic use case, using any range source with just the `from` and `to` parameters will provide a series of numeric arguments with a difference of 1 between them, beginning at `from` ending at the last value smaller than `to` (i.e. _excluding_ `to`).

[source,java,indent=0]
----
include::{demo}[tag=rangesources_int_valid_digit]
----

== Defining the step

The `step` argument allows controlling the difference between the consecutive values.
It can be positive or negative:

[source,java,indent=0]
----
include::{demo}[tag=rangesources_double_with_step]
----

== Open and closed range sources

By default, range sources represent ranges that are inclusive of the starting point (the `from` value), and exclusive of the end point (the `to` value).
This behavior can be controlled by specifying the `closed` argument:

[source,java,indent=0]
----
include::{demo}[tag=rangesources_ranges]
----

== Empty ranges

The range sources check whether the range defined by `from`, `to`, and `step` is empty and throws an `IllegalArgumentException` if it is.

== Thread-Safety

This extension is safe to use during https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution[parallel test execution].
