:page-title: @RepeatFailedTest
:page-description: Repeats a failing test a certain number of times; only marking it failed if none of them pass

Some tests, e.g. those depending on external systems, may fail through no fault of the code under test.
Such tests make a suite fragile and it makes sense to try and avoid them, but if that is not possible, it may help to retry a number of times before eventually assuming actual failure.
`@RepeatFailedTest` provides that functionality.

== Basic Use

`@RepeatFailedTest(n)` is used instead of `@Test` or other such annotations (e.g. `@RepeatedTest`).
The attribute `n` specifies how often the test is executed before giving up.

```java
@RepeatFailedTest(3)
void failsNever() {
    // passing test code
}
```

The test `failsNever` is executed once (which succeeds) and marked as passed.

```java
@RepeatFailedTest(3)
void failsOnlyOnFirstInvocation() {
    // test code that fails on first execution
    // but passes on the second
}
```

The test `failsOnlyOnFirstInvocation` is executed once (which fails) and then once more (which succeeds).
To allow the entire test suite to pass, the first execution isn't marked as having failed and so _both_ executions are marked as passing.

```
@RepeatFailedTest(3)
void failsAlways() {
    // test code that always fails
}
```

The test `failsAlways` is executed three times (all of which fail).
The first two executions are marked as passing and the last as failed.
The last execution is also the one listing all exceptions.
