:page-title: Standard Input and Output
:page-description: Extends JUnit Jupiter with `@StdIo`, which simulates standard input or catches standard output.
:xp-demo-dir: ../src/demo/java
:demo: {xp-demo-dir}/org/junitpioneer/jupiter/StdInOutExtensionDemo.java

The standard IO extension adds a simple way to test classes that read from the standard input (`System.in`) or write to the standard output (`System.out`).

WARNING: Depending on the configuration, the extension redirects the standard input and/or output, in which case nothing gets forwarded to the original `System.in` and/or `System.out`.
This becomes particularly important when running tests in parallel, where other tests may interfere with tests annotated with `@StdIo`.

== Basic use

The extension consists of two parts:

* The annotation `@StdIo`. It allows defining input that is read from `System.in` without having to wait for user input.
* Parameters `StdIn` and `StdOut`, which you can have injected into your test.
  Their `capturedLines()` methods allow you to access lines read from `System.in` or written to `System.out`, so you can verify them with common assertions.

For example, after calling `System.out.println("Hello")` and `System.out.println("World")`,  the `StdOut::capturedLines` method would return an array ["Hello", "World"].
With `System.out.print("Hello")` and `System.out.println("World")` (note that the first method does not print a line break), it would return `["HelloWorld"]`.

Here are the valid combinations of the annotation (with or without values for the read lines) and parameters:

`@StdIo("...")`::
In this case `System.in` gets replaced and the code under test will read the specified lines (in the snippet, that's just the line `"..."`).
+
[source,java,indent=0]
----
include::{demo}[tag=stdio_stdin_replace_input]
----

`@StdIo("...")` and `StdIn`::
Like before, but the lines read by the code under test can be verified with the `StdIn` parameter.
+
[source,java,indent=0]
----
include::{demo}[tag=stdio_stdin_replace__and_verify_input]
----

`@StdIo` and `StdOut`::
`System.in` is _not_ replaced (because no input lines are defined), but `System.out` is, so the written lines can be verified with the `StdOut` parameter.
+
[source,java,indent=0]
----
include::{demo}[tag=stdio_stdin_not_replaced_but_stdout]
----

`@StdIo("...")` and `StdOut`::
`System.in` is replaced, so the code can read the input lines and `System.out` is replaced, so the written lines can be verified with the `StdOut` parameter.
+
[source,java,indent=0]
----
include::{demo}[tag=stdio_both_replaced]
----

`@StdIo("...")`, `StdIn`, and `StdOut`::
A combination of the two previous cases - `System.in` and `System.out` get replaced.
+
[source,java,indent=0]
----
include::{demo}[tag=stdio_both_replaced_and_verify]
----

The remaining combinations of the annotation, its values, and `StdIn`/`StdOut` are considered misconfigurations and lead to exceptions.

== Thread-Safety

Since `System.in` and `System.out` are global state, reading and writing them during https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution[parallel test execution] can lead to unpredictable results and flaky tests.
The `@StdIo` extension is prepared for that and tests annotated with it will never execute in parallel (thanks to https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/parallel/ResourceLock.html[resource locks]) to guarantee correct test results.

However, this does not cover all possible cases.
Tested code that reads `System.in` or `System.out` or calls `System.setIn()` or `System.setOut()` _independently_ of the extensions can still run in parallel to them and may thus behave erratically when, for example, it unexpectedly uses `System.out` that was set by the extension in another thread.
Tests that cover code that reads or writes `System.in` or `System.out` need to be annotated with the respective annotation:

* `@ReadsStdIo`
* `@WritesStdIo`

Tests annotated in this way will never execute in parallel with tests annotated with `@StdIo`.

== Edge cases and unexpected behavior

=== Empty input (with or without `StdIn`)

Using just `@StdIo` does not redirect `System.in`, which means code reading from it will still block until input is provided and a `StdIn` parameter can't be resolved.
To have the code under test read empty input and/or use `StdIn` to verify that, use `@StdIo("")`.

=== Unexpected behavior with eager/buffering readers

Some readers read all lines from `StdIo` eagerly (e.g.: `BufferedReader`) which can lead to unexpected behavior.
Take the following example:

[source,java,indent=0]
----
include::{demo}[tag=stdio_edge_cases_ExampleConsoleReader]
----

This is a straightforward example class.
It reads two lines from `System.in`, using a `BufferedReader`.
This is the unit test for this class, using `StdIoExtension`:

[source,java,indent=0]
----
include::{demo}[tag=stdio_edge_cases_ConsoleReaderTest]
----

The underlying `BufferedReader` eagerly reads all three supplied lines during the first `readLine` call in the loop (that's why it's called _buffered_ reader).
This means that the assertion fails, because `in.capturedLines()` contains three lines - even though `consoleReader.lines` only contains two.
