:page-title: Standard Input and Output
:page-description: The JUnit 5 (Jupiter) extension `@StdIo` simulates standard input to `System.in` and captures standard output to `System.out` or `System.err` for assertions
:xp-demo-dir: ../src/demo/java
:demo: {xp-demo-dir}/org/junitpioneer/jupiter/StdInOutExtensionDemo.java

The standard IO extension adds a simple way to test classes that read from the standard input (`System.in`) or write to the standard output (`System.out` or `System.err`).
It redirects the original input/output streams to make predefined lines readable from `System.in` and to inject arguments that capture what was written to `System.out` or `System.err` for assertions.

[WARNING]
====
Depending on the configuration, the extension redirects the standard input and/or output, in which case nothing gets forwarded to the original `System.in` and/or `System.out` / `System.err`.
This becomes particularly important when running tests in parallel, where other tests may interfere with tests annotated with `@StdIo`.
More on that in the section _Thread-Safety_.
====

== Basic use

The extension consists of two parts:

* The annotation `@StdIo` enables the extension and optionally defines input that is read from `System.in` without having to wait for user input.
* The parameters `StdIn`, `StdOut`, and `StdErr` can be injected into your test.
  Their `capturedString()` and `capturedLines()` methods allow you to access the strings read from `System.in` or written to `System.out` or `System.err`, so you can verify them with common assertions.

For example, after calling `System.out.println("Hello")` and `System.out.println("World")`, `StdOut::capturedString` would return `"Hello%nWorld%n"`.
With `System.out.print("Hello")` and `System.out.println("World")` (note that the first method does not print a line break), the method would return `"HelloWorld%n"`.
(In both cases, `%n` corresponds to `System.getProperty("line.separator")`.)

=== Captured strings and lines

Since the strings passed to `@StdIo` or `System.out/err.print/println` don't need to end with a line separator, the question arises how they are separated for the purpose of `capturedString()`, i.e. how does the method's return distinguish between `println("Hello"); println("World");` and `print("Hello"); println("World");`?

[IMPORTANT]
====
This extension operates under the basic assumption that every string passed to `@StdIo`, `System.out.println`, or `System.err.println` implicitly ends with a line separator and hence adds it explicitly to the string returned by `capturedString()`.
This is not the case for strings passed to `System.out.print` and `System.err.print`.
====

The classes `StdIn`, `StdOut`, and `StdErr` also offer a method `String[] capturedLines()`, which divides the captured string on the line separator and includes leading, inner, and trailing empty lines but does not include the potential empty string that comes after a trailing line separator.
(The exact algorithm is based on but behaves differently from `String::split`.)

[WARNING]
====
The combination of these two approaches leads to the unfortunate situation that `capturedLines()` can't be used to distinguish the cases where the last line was created by a `print` or a `println` (see the first two lines in the table below) because regardless of whether the string ends with a line separator or not, there will be no trailing empty string in the array.
Use `capturedString()` to distinguish these cases.
====

Here are some examples to illustrate this behavior (`%n` corresponds to `System.getProperty("line.separator")`):

|===
| prints | `capturedString()` | `capturedLines()`

| `println("A");`                              | `"A%n"`        | `["A"]`
| `print("A");`                                | `"A"`          | `["A"]`
| `print("A");` `println("B");`                | `"AB%n"`       | `["AB"]`
| `println("A");` `println("B");`              | `"A%nB%n"`     | `["A", "B"]`
| `println("A");` `println();` `println("B");` | `"A%n%nB%n"`   | `["A", "", "B"]`
| `println();` `println("A");` `println();`    | `"%nA%n%n"`    | `["", "A", ""]`
|===

=== Valid configurations

Here are the valid combinations of the annotation (with or without values for the read lines) and parameters:

`@StdIo("...")`::
In this case `System.in` gets replaced and the code under test will read the specified lines (in the snippet, that's just the line `"..."`).
+
[source,java,indent=0]
----
include::{demo}[tag=stdio_stdin_replace_input]
----

`@StdIo("...")` and `StdIn`::
Like before, but the lines read by the code under test can be verified with the `StdIn` parameter.
+
[source,java,indent=0]
----
include::{demo}[tag=stdio_stdin_replace__and_verify_input]
----

`@StdIo` and `StdOut`::
`System.in` is _not_ replaced (because no input lines are defined), but `System.out` is, so the written lines can be verified with the `StdOut` parameter.
+
[source,java,indent=0]
----
include::{demo}[tag=stdio_stdin_not_replaced_but_stdout]
----

`@StdIo("...")` and `StdOut`::
`System.in` is replaced, so the code can read the input lines and `System.out` is replaced, so the written lines can be verified with the `StdOut` parameter.
+
[source,java,indent=0]
----
include::{demo}[tag=stdio_both_replaced]
----

`@StdIo("...")`, `StdIn`, and `StdOut`::
A combination of the two previous cases - `System.in` and `System.out` get replaced.
+
[source,java,indent=0]
----
include::{demo}[tag=stdio_both_replaced_and_verify]
----

NOTE: Omitted from these examples is `StdErr` which behaves exactly the same way as `StdOut` and works in combination with it.

The remaining combinations of the annotation, its values, and `StdIn`/`StdOut`/`StdErr` are considered misconfigurations and lead to exceptions.

== Thread-Safety

Since `System.in` and `System.out` are global state, reading and writing them during https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution[parallel test execution] can lead to unpredictable results and flaky tests.
The `@StdIo` extension is prepared for that and tests annotated with it will never execute in parallel (thanks to https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/parallel/ResourceLock.html[resource locks]) to guarantee correct test results.

However, this does not cover all possible cases.
Tested code that reads `System.in` or `System.out` or calls `System.setIn()` or `System.setOut()` _independently_ of the extensions can still run in parallel to them and may thus behave erratically if, for example, it unexpectedly uses `System.out` that was set by the extension in another thread.
Tests that cover code that reads or writes `System.in`, `System.out`, or `System.err` need to be annotated with the respective annotation:

* `@ReadsStdIo`
* `@WritesStdIo`

Tests annotated in this way will never execute in parallel with tests annotated with `@StdIo`.

== Edge cases and unexpected behavior

=== Empty input (with or without `StdIn`)

Using just `@StdIo` does not redirect `System.in`, which means code reading from it will still block until input is provided and a `StdIn` parameter can't be resolved.
To have the code under test read empty input and/or use `StdIn` to verify that, use `@StdIo("")`.

=== Unexpected behavior with eager/buffering readers

Some readers read all lines from `StdIo` eagerly (e.g.: `BufferedReader`) which can lead to unexpected behavior.
Take the following example:

[source,java,indent=0]
----
include::{demo}[tag=stdio_edge_cases_ExampleConsoleReader]
----

This is a straightforward example class.
It reads two lines from `System.in`, using a `BufferedReader`.
This is the unit test for this class, using `StdIoExtension`:

[source,java,indent=0]
----
include::{demo}[tag=stdio_edge_cases_ConsoleReaderTest]
----

The underlying `BufferedReader` eagerly reads all three supplied lines during the first `readLine` call in the loop (that's why it's called _buffered_ reader).
This means that the assertion fails, because `in.capturedLines()` contains three lines - even though `consoleReader.lines` only contains two.
