:page-title: Clearing, Setting and Restoring System Properties
:page-description: The JUnit 5 (Jupiter) extensions `@ClearSystemProperty`, `@SetSystemProperty` and `@RestoreSystemProperties`	 clear/set/restore the values of system properties during a test
:xp-demo-dir: ../src/demo/java
:demo: {xp-demo-dir}/org/junitpioneer/jupiter/SystemPropertyExtensionDemo.java

== `@ClearSystemProperty` and `@SetSystemProperty`
The `@ClearSystemProperty` and `@SetSystemProperty` annotations can be used to clear and set, respectively, the values of system properties for a test execution.
Both annotations work on the test method and class level, are repeatable, combinable, and inherited from higher-level containers.
After the annotated method has been executed, the properties mentioned in the annotation will be restored to their original value or the value of the higher-level container, or will be cleared if they didn't have one before.
Other system properties that are changed during the test, are *not* restored (unless the `@RestoreSystemProperties` is used).

For example, clearing a system property for a test execution can be done as follows:

[source,java,indent=0]
----
include::{demo}[tag=systemproperty_clear_simple]
----

And setting a system property for a test execution:

[source,java,indent=0]
----
include::{demo}[tag=systemproperty_set_simple]
----

As mentioned before, both annotations are repeatable and they can also be combined:

[source,java,indent=0]
----
include::{demo}[tag=systemproperty_using_set_and_clear]

----

Note that class-level configurations are overwritten by method-level configurations:

[source,java,indent=0]
----
include::{demo}[tag=systemproperty_using_at_class_level]
----

[NOTE]
====
Method-level configurations are visible in both `@BeforeEach` setup methods and `@AfterEach` teardown methods (see https://junit.org/junit5/docs/current/user-guide/#extensions-execution-order-overview[user code and extension code execution order]).

Since v1.7.0, a class-level configuration means that the specified system properties are cleared/set before and reset after each individual test in the annotated class.
====

== `@RestoreSystemProperties`
When you need to modify system properties directly in your code, either for a parameterized tests or other custom requirements, `@RestoreSystemProperties` can be used to ensure system properties are restored.
`@RestoreSystemProperties` can be used on test methods or test classes to completely restores all system properties to their original state after a test or test class is complete.

In this example, `@RestoreSystemProperties` is used on a test method, so any change made in that method are restored:

[source,java,indent=0]
----
include::{demo}[tag=systemproperty_restore_test]
----

[NOTE]
====
`@ClearSystemProperty` and `@SetSystemProperty` cannot accept variables for values, so any type of calculated or parameterized value needs to be set in code.
====

When `@RestoreSystemProperties` is used on a test class, any changes made in `@BeforeAll` methods is restored after the test class is complete.
In addition, a class level annotation is inherited by each test method just as if each one was annotated with `@RestoreSystemProperties`.

In the following example, `SomeOtherTest` is completely isolated from changes made in `MySystemPropertyRestoreTest` and `isolatedTest2` is isolated from changes made in `isolatedTest1`.
Both `isolatedTest1` and `isolatedTest2` will see system property values set in `@BeforeAll` and `@BeforeEach`, however.

[source,java,indent=0]
----
include::{demo}[tag=systemproperty_restore_class_level]
----


When placed on a test method, a snapshot of system properties is stored prior to that test.
The snapshot is created before any `@BeforeEach` blocks in scope and before the effects of any `@SetSystemProperty` or `@ClearSystemProperty` annotations on that method.
After the test method, system properties are restored from the snapshot after any `@AfterEach` have completed.





== Thread-Safety

Since system properties are global state, reading and writing them during https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution[parallel test execution] can lead to unpredictable results and flaky tests.
The system property extension is prepared for that and tests annotated with `@ClearSystemProperty` or `@SetSystemProperty` will never execute in parallel (thanks to https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/parallel/ResourceLock.html[resource locks]) to guarantee correct test results.

However, this does not cover all possible cases.
Tested code that reads or writes system properties _independently_ of the extension can still run in parallel to it and may thus behave erratically when, for example, it unexpectedly reads a property set by the extension in another thread.
Tests that cover code that reads or writes system properties need to be annotated with the respective annotation:

* `@ReadsSystemProperty`
* `@WritesSystemProperty`

Tests annotated in this way will never execute in parallel with tests annotated with `@ClearSystemProperty` or `@SetSystemProperty`.
