:page-title: Injecting Temporary Directories
:page-description: The JUnit 5 (Jupiter) extension `@Dir` allows to create, share, and inject temporary directories as arguments
:xp-demo-dir: ../src/demo/java
:demo: {xp-demo-dir}/org/junitpioneer/jupiter/resource/ResourceExtensionDemo.java
:resources-doc: ./resources.adoc

A temporary directory is a directory on the machine's on-disk filesystem that is created for one or more tests and deleted when it is no longer needed.
Temporary directories are created via annotations on parameters and configure whether a directory is created anew for a test or shared with others.
Either way, they're deleted once they're no longer needed.
You can also configure the _prefix_ of a temporary directory's name, which might be useful for test reporting or debugging reasons.

[NOTE]
====
This article describes the specifics of how to inject temporary directories into your tests.
Most of the extension's features are shared with other resources, though, and are described in link:/docs/resources[the article covering resources in general].
This includes important aspects like thread-safety, sharing resources, and cleaning up behind them (in this case, deleting the temporary directory), so make sure to read that one as well.

This temporary directory extension was introduced in JUnit Pioneer 1.9.0.
JUnit Pioneer versions before 1.0 contain link:/docs/temp-directory-removed[a then-removed temp dir extension], which was superseded by the very similar but more powerful https://junit.org/junit5/docs/current/user-guide/#writing-tests-built-in-extensions-TempDirectory[official `@TempDir` extension] shipped with JUnit Jupiter 5.4.
====

== Creating a New Temporary Directory

To create a new temporary directory for a given test:

[source,java,indent=0]
----
include::{demo}[tag=create_new_dir_demo]
----

`@Dir` is the shorthand annotation for `@New`, meaning it achieves the same result more succinctly than the long form:

[source,java,indent=0]
----
include::{demo}[tag=create_new_resources_demo]
----

== Creating with Arguments

To specify the _prefix_ of a new temporary directory's name, pass the prefix as an argument to the `@New` annotation:

[source,java,indent=0]
----
include::{demo}[tag=create_new_resource_with_arg_demo]
----

[NOTE]
====
The `@Dir` annotation does not yet support arguments.
Follow https://github.com/junit-pioneer/junit-pioneer/issues/648[this issue] for updates on this feature.
====

== Sharing a Temporary Directory

To create a temporary directory that is shared by multiple tests:

[source,java,indent=0]
----
include::{demo}[tag=create_shared_resource_demo]
----

See the link:/docs/resources#sharing_a_resource[Resources documentation] for more information.

[NOTE]
====
There's no shorthand form of `@Shared`.
Follow https://github.com/junit-pioneer/junit-pioneer/issues/648[this issue] for updates on this feature.
====

== Thread-Safety

This extension is safe to use during parallel test execution.

Tests with `@New` temporary directories will continue to run in parallel.
Tests with `@Shared` temporary directories will be forced to run *sequentially*, even if parallel execution has been enabled.
